# {
#     "id": 6445528187187,
#     "admin_graphql_api_id": "gid://shopify/Order/6445528187187",
#     "app_id": 1354745,
#     "browser_ip": "27.109.22.14",
#     "buyer_accepts_marketing": False,
#     "cancel_reason": None,
#     "cancelled_at": None,
#     "cart_token": None,
#     "checkout_id": 39181574701363,
#     "checkout_token": "145c8a8842ef223c8636bd33fce50110",
#     "client_details": {
#         "accept_language": None,
#         "browser_height": None,
#         "browser_ip": "27.109.22.14",
#         "browser_width": None,
#         "session_hash": None,
#         "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36 Edg/136.0.0.0",
#     },
#     "closed_at": None,
#     "company": None,
#     "confirmation_number": "UG68H1E1T",
#     "confirmed": True,
#     "contact_email": "parth308@gmail.com",
#     "created_at": "2025-05-30T06:16:52-04:00",
#     "currency": "INR",
#     "current_shipping_price_set": {
#         "shop_money": {"amount": "0.00", "currency_code": "INR"},
#         "presentment_money": {"amount": "0.00", "currency_code": "INR"},
#     },
#     "current_subtotal_price": "100.00",
#     "current_subtotal_price_set": {
#         "shop_money": {"amount": "100.00", "currency_code": "INR"},
#         "presentment_money": {"amount": "100.00", "currency_code": "INR"},
#     },
#     "current_total_additional_fees_set": None,
#     "current_total_discounts": "0.00",
#     "current_total_discounts_set": {
#         "shop_money": {"amount": "0.00", "currency_code": "INR"},
#         "presentment_money": {"amount": "0.00", "currency_code": "INR"},
#     },
#     "current_total_duties_set": None,
#     "current_total_price": "118.00",
#     "current_total_price_set": {
#         "shop_money": {"amount": "118.00", "currency_code": "INR"},
#         "presentment_money": {"amount": "118.00", "currency_code": "INR"},
#     },
#     "current_total_tax": "18.00",
#     "current_total_tax_set": {
#         "shop_money": {"amount": "18.00", "currency_code": "INR"},
#         "presentment_money": {"amount": "18.00", "currency_code": "INR"},
#     },
#     "customer_locale": "en",
#     "device_id": None,
#     "discount_codes": [],
#     "duties_included": False,
#     "email": "parth308@gmail.com",
#     "estimated_taxes": False,
#     "financial_status": "pending",
#     "fulfillment_status": None,
#     "landing_site": None,
#     "landing_site_ref": None,
#     "location_id": None,
#     "merchant_business_entity_id": None,
#     "merchant_of_record_app_id": None,
#     "name": "#1012",
#     "note": None,
#     "note_attributes": [],
#     "number": 12,
#     "order_number": 1012,
#     "order_status_url": "https://solufydevelop.myshopify.com/94319575347/orders/d3efaeb8b4281ccba8c8e1d348aa2d8b/authenticate?key=c09c862789995624b1fcbfda698fba66",
#     "original_total_additional_fees_set": None,
#     "original_total_duties_set": None,
#     "payment_gateway_names": [],
#     "phone": "+918569742360",
#     "po_number": None,
#     "presentment_currency": "INR",
#     "processed_at": "2025-05-30T06:16:51-04:00",
#     "reference": None,
#     "referring_site": None,
#     "source_identifier": None,
#     "source_name": "shopify_draft_order",
#     "source_url": None,
#     "subtotal_price": "100.00",
#     "subtotal_price_set": {
#         "shop_money": {"amount": "100.00", "currency_code": "INR"},
#         "presentment_money": {"amount": "100.00", "currency_code": "INR"},
#     },
#     "tags": "",
#     "tax_exempt": False,
#     "tax_lines": [
#         {
#             "price": "18.00",
#             "rate": 0.18,
#             "title": "IGST",
#             "price_set": {
#                 "shop_money": {"amount": "18.00", "currency_code": "INR"},
#                 "presentment_money": {"amount": "18.00", "currency_code": "INR"},
#             },
#             "channel_liable": False,
#         }
#     ],
#     "taxes_included": False,
#     "test": False,
#     "token": "d3efaeb8b4281ccba8c8e1d348aa2d8b",
#     "total_cash_rounding_payment_adjustment_set": {
#         "shop_money": {"amount": "0.00", "currency_code": "INR"},
#         "presentment_money": {"amount": "0.00", "currency_code": "INR"},
#     },
#     "total_cash_rounding_refund_adjustment_set": {
#         "shop_money": {"amount": "0.00", "currency_code": "INR"},
#         "presentment_money": {"amount": "0.00", "currency_code": "INR"},
#     },
#     "total_discounts": "0.00",
#     "total_discounts_set": {
#         "shop_money": {"amount": "0.00", "currency_code": "INR"},
#         "presentment_money": {"amount": "0.00", "currency_code": "INR"},
#     },
#     "total_line_items_price": "100.00",
#     "total_line_items_price_set": {
#         "shop_money": {"amount": "100.00", "currency_code": "INR"},
#         "presentment_money": {"amount": "100.00", "currency_code": "INR"},
#     },
#     "total_outstanding": "118.00",
#     "total_price": "118.00",
#     "total_price_set": {
#         "shop_money": {"amount": "118.00", "currency_code": "INR"},
#         "presentment_money": {"amount": "118.00", "currency_code": "INR"},
#     },
#     "total_shipping_price_set": {
#         "shop_money": {"amount": "0.00", "currency_code": "INR"},
#         "presentment_money": {"amount": "0.00", "currency_code": "INR"},
#     },
#     "total_tax": "18.00",
#     "total_tax_set": {
#         "shop_money": {"amount": "18.00", "currency_code": "INR"},
#         "presentment_money": {"amount": "18.00", "currency_code": "INR"},
#     },
#     "total_tip_received": "0.00",
#     "total_weight": 0,
#     "updated_at": "2025-05-30T06:18:41-04:00",
#     "user_id": 119435231539,
#     "billing_address": {
#         "first_name": "Parthrajsinh",
#         "address1": "201 Maninagar Road Khokhra",
#         "phone": "+91 85697 42360",
#         "city": "Ahmedabad",
#         "zip": "380008",
#         "province": "Gujarat",
#         "country": "India",
#         "last_name": "Jadeja",
#         "address2": "Maninagar",
#         "company": None,
#         "latitude": 22.9943004,
#         "longitude": 72.6138371,
#         "name": "Parthrajsinh Jadeja",
#         "country_code": "IN",
#         "province_code": "GJ",
#     },
#     "customer": {
#         "id": 8828162769203,
#         "email": "parth308@gmail.com",
#         "created_at": "2025-05-29T02:57:06-04:00",
#         "updated_at": "2025-05-30T06:16:52-04:00",
#         "first_name": "Parthrajsinh",
#         "last_name": "Jadeja",
#         "state": "disabled",
#         "note": "",
#         "verified_email": True,
#         "multipass_identifier": None,
#         "tax_exempt": False,
#         "phone": "+918569742360",
#         "currency": "INR",
#         "tax_exemptions": [],
#         "admin_graphql_api_id": "gid://shopify/Customer/8828162769203",
#         "default_address": {
#             "id": 10706146885939,
#             "customer_id": 8828162769203,
#             "first_name": "Parthrajsinh",
#             "last_name": "Jadeja",
#             "company": None,
#             "address1": "201 Maninagar Road Khokhra",
#             "address2": "Maninagar",
#             "city": "Ahmedabad",
#             "province": "Gujarat",
#             "country": "India",
#             "zip": "380008",
#             "phone": "+91 85697 42360",
#             "name": "Parthrajsinh Jadeja",
#             "province_code": "GJ",
#             "country_code": "IN",
#             "country_name": "India",
#             "default": True,
#         },
#     },
#     "discount_applications": [],
#     "fulfillments": [],
#     "line_items": [
#         {
#             "id": 15976766308659,
#             "admin_graphql_api_id": "gid://shopify/LineItem/15976766308659",
#             "attributed_staffs": [],
#             "current_quantity": 1,
#             "fulfillable_quantity": 1,
#             "fulfillment_service": "manual",
#             "fulfillment_status": None,
#             "gift_card": False,
#             "grams": 0,
#             "name": "Pens - Black",
#             "price": "100.00",
#             "price_set": {
#                 "shop_money": {"amount": "100.00", "currency_code": "INR"},
#                 "presentment_money": {"amount": "100.00", "currency_code": "INR"},
#             },
#             "product_exists": True,
#             "product_id": 9757449552179,
#             "properties": [],
#             "quantity": 1,
#             "requires_shipping": True,
#             "sales_line_item_group_id": None,
#             "sku": "",
#             "taxable": True,
#             "title": "Pens",
#             "total_discount": "0.00",
#             "total_discount_set": {
#                 "shop_money": {"amount": "0.00", "currency_code": "INR"},
#                 "presentment_money": {"amount": "0.00", "currency_code": "INR"},
#             },
#             "variant_id": 51591988937011,
#             "variant_inventory_management": "shopify",
#             "variant_title": "Black",
#             "vendor": "SolufyDevelop",
#             "tax_lines": [
#                 {
#                     "channel_liable": False,
#                     "price": "18.00",
#                     "price_set": {
#                         "shop_money": {"amount": "18.00", "currency_code": "INR"},
#                         "presentment_money": {
#                             "amount": "18.00",
#                             "currency_code": "INR",
#                         },
#                     },
#                     "rate": 0.18,
#                     "title": "IGST",
#                 }
#             ],
#             "duties": [],
#             "discount_allocations": [],
#         }
#     ],
#     "payment_terms": {
#         "id": 34165195059,
#         "created_at": "2025-05-30T06:16:52-04:00",
#         "due_in_days": None,
#         "payment_schedules": [],
#         "payment_terms_name": "Due on receipt",
#         "payment_terms_type": "receipt",
#         "updated_at": "2025-05-30T06:16:52-04:00",
#     },
#     "refunds": [],
#     "shipping_address": {
#         "first_name": "Parthrajsinh",
#         "address1": "201 Maninagar Road Khokhra",
#         "phone": "+91 85697 42360",
#         "city": "Ahmedabad",
#         "zip": "380008",
#         "province": "Gujarat",
#         "country": "India",
#         "last_name": "Jadeja",
#         "address2": "Maninagar",
#         "company": None,
#         "latitude": 22.9943004,
#         "longitude": 72.6138371,
#         "name": "Parthrajsinh Jadeja",
#         "country_code": "IN",
#         "province_code": "GJ",
#     },
#     "shipping_lines": [],
#     "returns": [],
# }


# ################################

# {
#     "id": 6445470515507,
#     "admin_graphql_api_id": "gid://shopify/Order/6445470515507",
#     "app_id": 1354745,
#     "browser_ip": "27.109.22.14",
#     "buyer_accepts_marketing": False,
#     "cancel_reason": None,
#     "cancelled_at": None,
#     "cart_token": None,
#     "checkout_id": 39181250429235,
#     "checkout_token": "0bf23831e1b7fe07bdfd6f9fa3a01178",
#     "client_details": {
#         "accept_language": None,
#         "browser_height": None,
#         "browser_ip": "27.109.22.14",
#         "browser_width": None,
#         "session_hash": None,
#         "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36 Edg/136.0.0.0",
#     },
#     "closed_at": None,
#     "company": None,
#     "confirmation_number": "139HA87RU",
#     "confirmed": True,
#     "contact_email": "rriya1807@gmail.com",
#     "created_at": "2025-05-30T04:53:39-04:00",
#     "currency": "INR",
#     "current_shipping_price_set": {
#         "shop_money": {"amount": "0.00", "currency_code": "INR"},
#         "presentment_money": {"amount": "0.00", "currency_code": "INR"},
#     },
#     "current_subtotal_price": "5000.00",
#     "current_subtotal_price_set": {
#         "shop_money": {"amount": "5000.00", "currency_code": "INR"},
#         "presentment_money": {"amount": "5000.00", "currency_code": "INR"},
#     },
#     "current_total_additional_fees_set": None,
#     "current_total_discounts": "0.00",
#     "current_total_discounts_set": {
#         "shop_money": {"amount": "0.00", "currency_code": "INR"},
#         "presentment_money": {"amount": "0.00", "currency_code": "INR"},
#     },
#     "current_total_duties_set": None,
#     "current_total_price": "5900.00",
#     "current_total_price_set": {
#         "shop_money": {"amount": "5900.00", "currency_code": "INR"},
#         "presentment_money": {"amount": "5900.00", "currency_code": "INR"},
#     },
#     "current_total_tax": "900.00",
#     "current_total_tax_set": {
#         "shop_money": {"amount": "900.00", "currency_code": "INR"},
#         "presentment_money": {"amount": "900.00", "currency_code": "INR"},
#     },
#     "customer_locale": "en",
#     "device_id": None,
#     "discount_codes": [],
#     "duties_included": False,
#     "email": "rriya1807@gmail.com",
#     "estimated_taxes": False,
#     "financial_status": "paid",
#     "fulfillment_status": None,
#     "landing_site": None,
#     "landing_site_ref": None,
#     "location_id": None,
#     "merchant_business_entity_id": None,
#     "merchant_of_record_app_id": None,
#     "name": "#1009",
#     "note": None,
#     "note_attributes": [],
#     "number": 9,
#     "order_number": 1009,
#     "order_status_url": "https://solufydevelop.myshopify.com/94319575347/orders/95ee492d67a6569988646740ff31ab01/authenticate?key=30da504d72e750e5706dc90ac2e80793",
#     "original_total_additional_fees_set": None,
#     "original_total_duties_set": None,
#     "payment_gateway_names": ["manual"],
#     "phone": "+919856321470",
#     "po_number": None,
#     "presentment_currency": "INR",
#     "processed_at": "2025-05-30T04:53:39-04:00",
#     "reference": None,
#     "referring_site": None,
#     "source_identifier": None,
#     "source_name": "shopify_draft_order",
#     "source_url": None,
#     "subtotal_price": "5000.00",
#     "subtotal_price_set": {
#         "shop_money": {"amount": "5000.00", "currency_code": "INR"},
#         "presentment_money": {"amount": "5000.00", "currency_code": "INR"},
#     },
#     "tags": "",
#     "tax_exempt": False,
#     "tax_lines": [
#         {
#             "price": "900.00",
#             "rate": 0.18,
#             "title": "IGST",
#             "price_set": {
#                 "shop_money": {"amount": "900.00", "currency_code": "INR"},
#                 "presentment_money": {"amount": "900.00", "currency_code": "INR"},
#             },
#             "channel_liable": False,
#         }
#     ],
#     "taxes_included": False,
#     "test": False,
#     "token": "95ee492d67a6569988646740ff31ab01",
#     "total_cash_rounding_payment_adjustment_set": {
#         "shop_money": {"amount": "0.00", "currency_code": "INR"},
#         "presentment_money": {"amount": "0.00", "currency_code": "INR"},
#     },
#     "total_cash_rounding_refund_adjustment_set": {
#         "shop_money": {"amount": "0.00", "currency_code": "INR"},
#         "presentment_money": {"amount": "0.00", "currency_code": "INR"},
#     },
#     "total_discounts": "0.00",
#     "total_discounts_set": {
#         "shop_money": {"amount": "0.00", "currency_code": "INR"},
#         "presentment_money": {"amount": "0.00", "currency_code": "INR"},
#     },
#     "total_line_items_price": "5000.00",
#     "total_line_items_price_set": {
#         "shop_money": {"amount": "5000.00", "currency_code": "INR"},
#         "presentment_money": {"amount": "5000.00", "currency_code": "INR"},
#     },
#     "total_outstanding": "0.00",
#     "total_price": "5900.00",
#     "total_price_set": {
#         "shop_money": {"amount": "5900.00", "currency_code": "INR"},
#         "presentment_money": {"amount": "5900.00", "currency_code": "INR"},
#     },
#     "total_shipping_price_set": {
#         "shop_money": {"amount": "0.00", "currency_code": "INR"},
#         "presentment_money": {"amount": "0.00", "currency_code": "INR"},
#     },
#     "total_tax": "900.00",
#     "total_tax_set": {
#         "shop_money": {"amount": "900.00", "currency_code": "INR"},
#         "presentment_money": {"amount": "900.00", "currency_code": "INR"},
#     },
#     "total_tip_received": "0.00",
#     "total_weight": 0,
#     "updated_at": "2025-05-30T04:56:10-04:00",
#     "user_id": 119435231539,
#     "billing_address": {
#         "first_name": "Riya",
#         "address1": "Panjara Pol Ambawadi",
#         "phone": "+91 98563 21470",
#         "city": "Ahmedabad",
#         "zip": "380015",
#         "province": "Gujarat",
#         "country": "India",
#         "last_name": "Gupta",
#         "address2": "101, Shitanshu Appartment",
#         "company": "Solufy",
#         "latitude": 23.0267669,
#         "longitude": 72.5419263,
#         "name": "Riya Gupta",
#         "country_code": "IN",
#         "province_code": "GJ",
#     },
#     "customer": {
#         "id": 8828123087155,
#         "email": "rriya1807@gmail.com",
#         "created_at": "2025-05-29T02:26:38-04:00",
#         "updated_at": "2025-05-30T04:53:40-04:00",
#         "first_name": "Riya",
#         "last_name": "Gupta",
#         "state": "disabled",
#         "note": "",
#         "verified_email": True,
#         "multipass_identifier": None,
#         "tax_exempt": False,
#         "phone": "+919856321470",
#         "currency": "INR",
#         "tax_exemptions": [],
#         "admin_graphql_api_id": "gid://shopify/Customer/8828123087155",
#         "default_address": {
#             "id": 10707566821683,
#             "customer_id": 8828123087155,
#             "first_name": "Riya",
#             "last_name": "Gupta",
#             "company": "Solufy",
#             "address1": "Panjara Pol Ambawadi",
#             "address2": "101, Shitanshu Appartment",
#             "city": "Ahmedabad",
#             "province": "Gujarat",
#             "country": "India",
#             "zip": "380015",
#             "phone": "+91 98563 21470",
#             "name": "Riya Gupta",
#             "province_code": "GJ",
#             "country_code": "IN",
#             "country_name": "India",
#             "default": True,
#         },
#     },
#     "discount_applications": [],
#     "fulfillments": [],
#     "line_items": [
#         {
#             "id": 15976678261043,
#             "admin_graphql_api_id": "gid://shopify/LineItem/15976678261043",
#             "attributed_staffs": [],
#             "current_quantity": 1,
#             "fulfillable_quantity": 1,
#             "fulfillment_service": "manual",
#             "fulfillment_status": None,
#             "gift_card": False,
#             "grams": 0,
#             "name": "Watch",
#             "price": "5000.00",
#             "price_set": {
#                 "shop_money": {"amount": "5000.00", "currency_code": "INR"},
#                 "presentment_money": {"amount": "5000.00", "currency_code": "INR"},
#             },
#             "product_exists": True,
#             "product_id": 9757338861875,
#             "properties": [],
#             "quantity": 1,
#             "requires_shipping": True,
#             "sales_line_item_group_id": None,
#             "sku": "",
#             "taxable": True,
#             "title": "Watch",
#             "total_discount": "0.00",
#             "total_discount_set": {
#                 "shop_money": {"amount": "0.00", "currency_code": "INR"},
#                 "presentment_money": {"amount": "0.00", "currency_code": "INR"},
#             },
#             "variant_id": 51591532511539,
#             "variant_inventory_management": "shopify",
#             "variant_title": None,
#             "vendor": "SolufyDevelop",
#             "tax_lines": [
#                 {
#                     "channel_liable": False,
#                     "price": "900.00",
#                     "price_set": {
#                         "shop_money": {"amount": "900.00", "currency_code": "INR"},
#                         "presentment_money": {
#                             "amount": "900.00",
#                             "currency_code": "INR",
#                         },
#                     },
#                     "rate": 0.18,
#                     "title": "IGST",
#                 }
#             ],
#             "duties": [],
#             "discount_allocations": [],
#         }
#     ],
#     "payment_terms": {
#         "id": 34161754419,
#         "created_at": "2025-05-30T04:53:40-04:00",
#         "due_in_days": None,
#         "payment_schedules": [],
#         "payment_terms_name": "Due on receipt",
#         "payment_terms_type": "receipt",
#         "updated_at": "2025-05-30T04:53:40-04:00",
#     },
#     "refunds": [],
#     "shipping_address": {
#         "first_name": "Riya",
#         "address1": "Panjara Pol Ambawadi",
#         "phone": "+91 98563 21470",
#         "city": "Ahmedabad",
#         "zip": "380015",
#         "province": "Gujarat",
#         "country": "India",
#         "last_name": "Gupta",
#         "address2": "101, Shitanshu Appartment",
#         "company": "Solufy",
#         "latitude": 23.0267669,
#         "longitude": 72.5419263,
#         "name": "Riya Gupta",
#         "country_code": "IN",
#         "province_code": "GJ",
#     },
#     "shipping_lines": [],
#     "returns": [],
# }
