// [
//     {
//         "id": 72219492463,
//         "name": "Jupiter Fulfillment",
//         "address1": "",
//         "address2": "",
//         "city": "Default City",
//         "zip": "000000",
//         "province": "Gujarat",
//         "country": "IN",
//         "phone": "",
//         "created_at": "2025-05-14T13:09:03+05:30",
//         "updated_at": "2025-05-15T23:23:31+05:30",
//         "country_code": "IN",
//         "country_name": "India",
//         "province_code": "GJ",
//         "legacy": True,
//         "active": True,
//         "admin_graphql_api_id": "gid://shopify/Location/72219492463",
//         "localized_country_name": "India",
//         "localized_province_name": "Gujarat",
//     },
//     {
//         "id": 72261337199,
//         "name": "Jupiter Fulfillment - SD",
//         "address1": "",
//         "address2": "",
//         "city": "Default City",
//         "zip": "000000",
//         "province": "Gujarat",
//         "country": "IN",
//         "phone": "",
//         "created_at": "2025-05-16T10:34:36+05:30",
//         "updated_at": "2025-05-16T10:34:38+05:30",
//         "country_code": "IN",
//         "country_name": "India",
//         "province_code": "GJ",
//         "legacy": False,
//         "active": True,
//         "admin_graphql_api_id": "gid://shopify/Location/72261337199",
//         "localized_country_name": "India",
//         "localized_province_name": "Gujarat",
//     },
//     {
//         "id": 72219656303,
//         "name": "Kumail",
//         "address1": "",
//         "address2": "",
//         "city": "Default City",
//         "zip": "000000",
//         "province": "Gujarat",
//         "country": "IN",
//         "phone": "",
//         "created_at": "2025-05-14T13:12:07+05:30",
//         "updated_at": "2025-05-15T23:28:21+05:30",
//         "country_code": "IN",
//         "country_name": "India",
//         "province_code": "GJ",
//         "legacy": True,
//         "active": True,
//         "admin_graphql_api_id": "gid://shopify/Location/72219656303",
//         "localized_country_name": "India",
//         "localized_province_name": "Gujarat",
//     },
//     {
//         "id": 72228798575,
//         "name": "Kumail - SD",
//         "address1": "Default Address",
//         "address2": None,
//         "city": "Default City",
//         "zip": "000000",
//         "province": "Gujarat",
//         "country": "IN",
//         "phone": None,
//         "created_at": "2025-05-14T22:23:29+05:30",
//         "updated_at": "2025-05-14T22:23:30+05:30",
//         "country_code": "IN",
//         "country_name": "India",
//         "province_code": "GJ",
//         "legacy": False,
//         "active": True,
//         "admin_graphql_api_id": "gid://shopify/Location/72228798575",
//         "localized_country_name": "India",
//         "localized_province_name": "Gujarat",
//     },
//     {
//         "id": 72219820143,
//         "name": "Kumail Erp",
//         "address1": "Solufy Gandhinagar",
//         "address2": None,
//         "city": "Gandhinagar",
//         "zip": "382421",
//         "province": "Gujarat",
//         "country": "IN",
//         "phone": None,
//         "created_at": "2025-05-14T13:17:04+05:30",
//         "updated_at": "2025-05-14T13:17:05+05:30",
//         "country_code": "IN",
//         "country_name": "India",
//         "province_code": "GJ",
//         "legacy": False,
//         "active": True,
//         "admin_graphql_api_id": "gid://shopify/Location/72219820143",
//         "localized_country_name": "India",
//         "localized_province_name": "Gujarat",
//     },
//     {
//         "id": 72219951215,
//         "name": "Kumail Erp123",
//         "address1": "Solufy Gandhinagar",
//         "address2": None,
//         "city": "Gandhinagar",
//         "zip": "382421",
//         "province": "Gujarat",
//         "country": "IN",
//         "phone": None,
//         "created_at": "2025-05-14T13:25:50+05:30",
//         "updated_at": "2025-05-14T13:25:50+05:30",
//         "country_code": "IN",
//         "country_name": "India",
//         "province_code": "GJ",
//         "legacy": False,
//         "active": True,
//         "admin_graphql_api_id": "gid://shopify/Location/72219951215",
//         "localized_country_name": "India",
//         "localized_province_name": "Gujarat",
//     },
//     {
//         "id": 72243937391,
//         "name": "Mobile Warehouse - SD",
//         "address1": "",
//         "address2": "301, Solufy Shiddraj ZavodSargasan",
//         "city": "Gandhinagar",
//         "zip": "000000",
//         "province": "Gujarat",
//         "country": "IN",
//         "phone": "9313406891",
//         "created_at": "2025-05-15T15:56:56+05:30",
//         "updated_at": "2025-05-15T15:56:57+05:30",
//         "country_code": "IN",
//         "country_name": "India",
//         "province_code": "GJ",
//         "legacy": False,
//         "active": True,
//         "admin_graphql_api_id": "gid://shopify/Location/72243937391",
//         "localized_country_name": "India",
//         "localized_province_name": "Gujarat",
//     },
//     {
//         "id": 70778880111,
//         "name": "My Custom Location",
//         "address1": "Solufy Sector 2C Sector 2",
//         "address2": "Plot No 1557",
//         "city": "Gandhinagar",
//         "zip": "382002",
//         "province": "Gujarat",
//         "country": "IN",
//         "phone": "+918460220310",
//         "created_at": "2025-03-04T15:33:52+05:30",
//         "updated_at": "2025-05-02T16:11:33+05:30",
//         "country_code": "IN",
//         "country_name": "India",
//         "province_code": "GJ",
//         "legacy": False,
//         "active": True,
//         "admin_graphql_api_id": "gid://shopify/Location/70778880111",
//         "localized_country_name": "India",
//         "localized_province_name": "Gujarat",
//     },
//     {
//         "id": 72219754607,
//         "name": "New York Warehouses",
//         "address1": "101 Liberty Street",
//         "address2": None,
//         "city": "New York",
//         "zip": "10006",
//         "province": "New York",
//         "country": "US",
//         "phone": None,
//         "created_at": "2025-05-14T13:15:19+05:30",
//         "updated_at": "2025-05-14T13:15:19+05:30",
//         "country_code": "US",
//         "country_name": "United States",
//         "province_code": "NY",
//         "legacy": False,
//         "active": True,
//         "admin_graphql_api_id": "gid://shopify/Location/72219754607",
//         "localized_country_name": "United States",
//         "localized_province_name": "New York",
//     },
//     {
//         "id": 70778847343,
//         "name": "Shop location",
//         "address1": None,
//         "address2": None,
//         "city": None,
//         "zip": None,
//         "province": None,
//         "country": "IN",
//         "phone": None,
//         "created_at": "2025-03-04T15:33:07+05:30",
//         "updated_at": "2025-03-04T15:33:07+05:30",
//         "country_code": "IN",
//         "country_name": "India",
//         "province_code": None,
//         "legacy": False,
//         "active": True,
//         "admin_graphql_api_id": "gid://shopify/Location/70778847343",
//         "localized_country_name": "India",
//         "localized_province_name": None,
//     },
//     {
//         "id": 72316354671,
//         "name": "Shop location - S",
//         "address1": "",
//         "address2": None,
//         "city": "Default City",
//         "zip": "000000",
//         "province": None,
//         "country": "IN",
//         "phone": "",
//         "created_at": "2025-05-19T11:00:16+05:30",
//         "updated_at": "2025-05-19T11:00:18+05:30",
//         "country_code": "IN",
//         "country_name": "India",
//         "province_code": None,
//         "legacy": False,
//         "active": True,
//         "admin_graphql_api_id": "gid://shopify/Location/72316354671",
//         "localized_country_name": "India",
//         "localized_province_name": None,
//     },
//     {
//         "id": 70778912879,
//         "name": "Snow City Warehouse",
//         "address1": None,
//         "address2": None,
//         "city": None,
//         "zip": None,
//         "province": None,
//         "country": "IN",
//         "phone": None,
//         "created_at": "2025-03-04T15:33:53+05:30",
//         "updated_at": "2025-03-04T15:33:53+05:30",
//         "country_code": "IN",
//         "country_name": "India",
//         "province_code": None,
//         "legacy": True,
//         "active": True,
//         "admin_graphql_api_id": "gid://shopify/Location/70778912879",
//         "localized_country_name": "India",
//         "localized_province_name": None,
//     },
//     {
//         "id": 72267989103,
//         "name": "Snow City Warehouse - S",
//         "address1": "",
//         "address2": None,
//         "city": "Default City",
//         "zip": "000000",
//         "province": None,
//         "country": "IN",
//         "phone": "",
//         "created_at": "2025-05-16T18:09:24+05:30",
//         "updated_at": "2025-05-16T18:09:26+05:30",
//         "country_code": "IN",
//         "country_name": "India",
//         "province_code": None,
//         "legacy": False,
//         "active": True,
//         "admin_graphql_api_id": "gid://shopify/Location/72267989103",
//         "localized_country_name": "India",
//         "localized_province_name": None,
//     },
//     {
//         "id": 72245608559,
//         "name": "Warehouse-1 - SD",
//         "address1": "",
//         "address2": "401",
//         "city": "Ahmedabad",
//         "zip": "363642",
//         "province": "Gujarat",
//         "country": "IN",
//         "phone": "+919126578000",
//         "created_at": "2025-05-15T17:40:50+05:30",
//         "updated_at": "2025-05-16T18:11:09+05:30",
//         "country_code": "IN",
//         "country_name": "India",
//         "province_code": "GJ",
//         "legacy": False,
//         "active": True,
//         "admin_graphql_api_id": "gid://shopify/Location/72245608559",
//         "localized_country_name": "India",
//         "localized_province_name": "Gujarat",
//     },
// ]


